apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-certs
  namespace: argocd
  labels:
    name: static-certs
spec:
  project: default
  source:
    repoURL: https://github.com/symmatree/tales.git
    targetRevision: main
    path: static-certs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: static-certs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
