apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: github-data-source-secret
  labels:
    grafana_datasource: "1"
type: Opaque
spec:
  itemPath: vaults/tales-secrets/items/tales-grafana-github-token
