apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-externalip-pool"
spec:
  blocks:
    # 10.0.5.0/24 and 10.0.6.0/24 are the internal Pod and Service ranges.
    - cidr: "10.0.7.0/24"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announce-everything
spec:
  # No serviceSelector, apply to all.
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  externalIPs: true
  loadBalancerIPs: true
