apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-data-source
    namespace: loki
    labels:
        grafana_datasource: "1"
data:
    datasource.yaml: |-
        apiVersion: 1
        datasources:
          - name: Loki
            uid: loki
            type: loki
            url: http://loki-gateway.loki.svc
            isDefault: false
