version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - /alloy
      - /argocd
      - /cert-manager
      - /cilium
      - /connect
      - /external-dns
      - /kubernetes-dashboard
      - /minio-operator
      - /static-certs
      - /tales-tenant
      - /grafana
      - /jupyterhub
      - /loki
      - /mimir
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directories:
      - /alloy
      - /argocd
      - /cert-manager
      - /cilium
      - /connect
      - /external-dns
      - /kubernetes-dashboard
      - /minio-operator
      - /static-certs
      - /tales-tenant
      - /grafana
      - /jupyterhub
      - /loki
      - /mimir
    ignore:
      - dependency-name: "argocd"
        versions: ["2.0.0"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
