# https://raw.githubusercontent.com/minio/operator/refs/tags/v7.1.1/helm/operator/values.yaml

tenant:
  tenant:
    name: tales-tenant
    configSecret:
      # Populated from onepassword
      name: tales-tenant-secret
      existingSecret: true

    certificate:
      externalCaCertSecret:
        - name: tales-tenant-ca-tls
          type: cert-manager.io/v1
      externalCertSecret:
        - name: tales-tenant-tls
          type: cert-manager.io/v1
      requestAutoCert: false

    exposeServices:
      minio: true
      console: true

    pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 4
        storageClassName: directpv-minio-dedicated
        # Provisioning 3x drives @ 549,755,813,880=(2Ti / 4) - 8
        # leaves 548,681,941,016 remaining; this is 1,073,872,872 bytes
        # (about 1G) less than expected.
        # = (2TiB / 4) rounded down, because directpv won't provision
        # every byte (despite "give minio full control" memes)
        # Note 05-03: Maybe this is XFS overhead?
        size: 511Gi

  ingress:
    api:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: real-cert
      ingressClassName: "cilium"
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio.local.symmatree.com
      host: minio.local.symmatree.com
      path: /
      pathType: Prefix
    console:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: real-cert
      ingressClassName: "cilium"
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio-console.local.symmatree.com
      host: minio-console.local.symmatree.com
      path: /
      pathType: Prefix
