# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # general text file...stuff.
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf

      # git repo defense
      - id: check-added-large-files
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      # Also checked by github but prevent locally.
      - id: no-commit-to-branch

      # filesystem checks
      # not a strong position but I'd like to think about it.
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-symlinks

      # Leaks and stuff
      - id: detect-private-key

      # Language specific
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
        exclude: ".*\\.helm\\.yaml"

  # This requires docker; local install is easier.
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.10.0
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  # Disabled because it does not currently pass, we will get there.
  # - repo: local
  #   hooks:
  #     # Requires apt-get install shellcheck
  #     - id: shellcheck
  #       name: shellcheck
  #       description: Test shell scripts with shellcheck
  #       entry: shellcheck
  #       language: python
  #       types: [shell]
  #       require_serial: true # shellcheck can detect sourcing this way
