# Use trust-manager to inject just the public key of the shared CA, named as minio expects.
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: operator-ca-tls-tales-tenant
spec:
  sources:
    - secret:
        name: tales-ca-tls
        key: ca.crt
  target:
    secret:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: minio-operator
