apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-data-source
  namespace: "{{ .Release.Namespace }}"
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        url: http://tempo-frontend.tempo.svc
        isDefault: false
