apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apprise
  namespace: argocd
  labels:
    name: apprise
spec:
  project: default
  source:
    repoURL: https://github.com/symmatree/tales.git
    targetRevision: main
    path: apprise
    plugin:
      env:
        - name: TK_ENV
          value: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: apprise
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
