apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: google-oauth-secret
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: vaults/tales-secrets/items/argocd-google-oauth
