apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-data-source-secret
  namespace: lgtm
  labels:
    grafana_datasource: "1"
type: Opaque
spec:
  itemPath: "vaults/tales-secrets/items/tales-grafana-github-token"
