apiVersion: v1
kind: ConfigMap
metadata:
    name: mimir-data-source
    namespace: lgtm
    labels:
        grafana_datasource: "1"
data:
    datasource.yaml: |-
        apiVersion: 1
        datasources:
          - name: Mimir
            uid: prom
            type: prometheus
            url: http://lgtm-mimir-nginx/prometheus
            isDefault: true
            jsonData:
              prometheusType: mimir
