apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trust-bundle  # The bundle name will also be used for the target
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: tales-ca-secret
      key: "ca.crt"
  target:
    configMap:
      key: "ca-certificates.crt"
    namespaceSelector:
      matchLabels:
        trust-bundle: "enabled"
