apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cert
  namespace: "{{ .Release.Namespace }}"
spec:
  acme:
    email: symmetry@pobox.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-staging
    solvers:
      - selector:
          dnsZones:
            - ad.local.symmatree.com
            - local.symmatree.com
        dns01:
          cloudDNS:
            project: symm-custodes
            serviceAccountSecretRef:
              name: clouddns-sa
              key: credential.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: real-cert
spec:
  acme:
    email: symmetry@pobox.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-real
    solvers:
      - selector:
          dnsZones:
            - ad.local.symmatree.com
            - local.symmatree.com
        dns01:
          cloudDNS:
            project: symm-custodes
            serviceAccountSecretRef:
              name: clouddns-sa
              key: credential.json
