apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tales-selfsigned-root
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tales-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: tales-ca
  subject:
    organizations:
      - Porter Farms
    organizationalUnits:
      - TalesCluster
  secretName: tales-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: tales-selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tales-ca-issuer
spec:
  ca:
    secretName: tales-ca-secret
