global:
  extraEnvFrom:
    - secretRef:
        name: lgtm-s3-creds
  extraEnv:
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/ca-certificates.crt
  extraVolumes:
    - name: ca-certificates
      configMap:
        name: trust-bundle
  extraVolumeMounts:
    - name: ca-certificates
      mountPath: /etc/ssl/certs
      readOnly: true

grafana:
  # https://github.com/grafana/helm-charts/blob/grafana-8.13.1/charts/grafana/values.yaml
  configMapAnnotations:
    argocd.argoproj.io/sync-options: Replace=true
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: real-cert
    hosts:
      - borgmon.local.symmatree.com
    tls:
      - secretName: grafana-tls
        hosts:
          - borgmon.local.symmatree.com
  persistence:
    enabled: true

  admin:
    existingSecret: "grafana-admin-user"
    userKey: username
    passwordKey: password

  plugins:
    - grafana-github-datasource
    - grafana-lokiexplore-app
    # - grafana-metricsdrilldown-app
    # - grafana-mqtt-datasource

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      folderAnnotation: "k8s-sidecar-target-directory"
      provider:
        folderUid: "sidecar"
        folder: "Sidecar"
        allowUiUpdates: true
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      searchNamespace: ALL
