# https://raw.githubusercontent.com/minio/operator/refs/tags/v7.1.1/helm/operator/values.yaml

operator:
  operator:
    replicaCount: 1
    env:
      # https://github.com/minio/operator/blob/master/docs/cert-manager.md#install-operator-with-auto-tls-disabled-for-sts
      - name: OPERATOR_STS_AUTO_TLS_ENABLED
        value: "off"
