apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directpv
  namespace: argocd
  labels:
    name: directpv
spec:
  project: default
  source:
    repoURL: https://github.com/symmatree/tales.git
    targetRevision: main
    path: directpv
  destination:
    server: https://kubernetes.default.svc
    namespace: directpv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: baseline
