apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: directpv.min.io/identity
        values:
          - directpv-min-io
metadata:
  finalizers:
    - foregroundDeletion
  labels:
    application-name: directpv.min.io
    application-type: CSIDriver
    directpv.min.io/created-by: kubectl-directpv
    directpv.min.io/version: v1beta1
  name: directpv-minio-dedicated
parameters:
  csi.storage.k8s.io/fstype: xfs
  directpv.min.io/use: minio
provisioner: directpv-min-io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: directpv.min.io/identity
        values:
          - directpv-min-io
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  finalizers:
    - foregroundDeletion
  labels:
    application-name: directpv.min.io
    application-type: CSIDriver
    directpv.min.io/created-by: kubectl-directpv
    directpv.min.io/version: v1beta1
  name: directpv-general
parameters:
  csi.storage.k8s.io/fstype: xfs
  directpv.min.io/use: general
provisioner: directpv-min-io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
