apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-data-source
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Mimir Alertmanager
        uid: alertmanager
        type: alertmanager
        url: http://mimir-nginx.mimir.svc/
        jsonData:
          implementation: mimir
          handleGrafanaManagedAlerts: true
