apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-data-source
  namespace: "{{ .Release.Namespace }}"
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Mimir
        uid: prom
        type: prometheus
        url: http://mimir-nginx.mimir.svc/prometheus
        isDefault: true
        jsonData:
          prometheusType: Mimir
          alertmanagerUid: alertmanager
        secureJsonData:
          tlsCACert: $__file{/etc/ssl/certs/ca-certificates.crt}
