apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: tales-tenant
spec:
  dnsNames:
    - "minio.tales-tenant"
    - "minio.tales-tenant.svc"
    - 'minio.tales-tenant.svc.cluster.local'
    - '*.minio.tales-tenant.svc.cluster.local'
    - '*.tales-tenant-hl.tales-tenant.svc.cluster.local'
    - '*.tales-tenant.minio.tales-tenant.svc.cluster.local'
    - minio.local.symmatree.com
    - minio-console.local.symmatree.com
  secretName: tales-tenant-tls
  issuerRef:
    name: tales-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: tales-tenant-tls
spec:
  sources:
  - secret:
      name: tales-ca-secret
      key: "ca.crt"
  target:
    secret:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        name: tales-tenant
