apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-core
  namespace: testns
spec:
  jobName: blackbox
  interval: 30s
  module: http_2xx
  prober:
    url: alloy-alloy-metrics-cluster.alloy.svc:12345
    path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
  targets:
    staticConfig:
      static:
        - http://hubitat.local.symmatree.com
