apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    name: external-dns
spec:
  project: default
  source:
    repoURL: https://github.com/symmatree/tales.git
    targetRevision: main
    path: external-dns
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        "pod-security.kubernetes.io/warn": baseline
