# Started from
# https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/tags/external-dns-helm-chart-1.16.1/charts/external-dns/values.yaml

external-dns:
  serviceMonitor:
    # -- If `true`, create a `ServiceMonitor` resource to support the _Prometheus Operator_.
    enabled: true

  # -- Log format.
  logFormat: text  # @schema enum:["text", "json"]; type:string; default: "text"

  # -- Interval for DNS updates.
  interval: 1m

  # -- How DNS records are synchronized between sources and providers; available values are `sync` & `upsert-only`.
  policy: upsert-only  # @schema enum:[sync, upsert-only]; type:string; default: "upsert-only"

  # -- Specify the registry for storing ownership and labels.
  # Valid values are `txt`, `aws-sd`, `dynamodb` & `noop`.
  registry: txt  # @schema enum:[txt, aws-sd, dynamodb, noop]; default: "txt"
  # -- (string) Specify an identifier for this instance of _ExternalDNS_ wWhen using a registry other than `noop`.
  txtOwnerId:  tales

  # -- Limit possible target zones by domain suffixes.
  domainFilters:
  - local.symmatree.com
  - 0.10.in-addr.arpa

  provider:  # @schema type: [object, string];
    # -- _ExternalDNS_ provider name; for the available providers and how to configure them see [README](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers).
    name: rfc2136
  env:
  - name: TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: TSIG_SECRET
  - name: TSIG_SECRET_ALG
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: TSIG_SECRET_ALG
  - name: TSIG_KEYNAME
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: TSIG_KEYNAME

  # -- Extra arguments to provide to _ExternalDNS_.
  extraArgs:
    - --rfc2136-host=10.0.99.1
    - --rfc2136-port=53
    - --rfc2136-zone=local.symmatree.com
    - --rfc2136-zone=0.10.in-addr.arpa
    - --rfc2136-tsig-secret=$(TSIG_SECRET)
    - --rfc2136-tsig-secret-alg=$(TSIG_SECRET_ALG)
    - --rfc2136-tsig-keyname=$(TSIG_SECRET_KEYNAME)
    - --rfc2136-tsig-axfr 
    - --rfc2136-create-ptr
