tempo:
  extraVolumes:
    - name: ca-certificates
      configMap:
        name: trust-bundle
  replicas: 1
  persistence:
    enabled: true
    enableStatefulSetAutoDeletePVC: true
  serviceMonitor:
    enabled: true
  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-storage
          endpoint: minio.tales-tenant.svc:443
          # For unclear reasons the Kubernetes dollar-paren syntax is not
          # expanded but this is Loki's native expansion syntax with config.expand-env=true
          access_key: ${ACCESS_KEY_ID}
          secret_key: ${SECRET_ACCESS_KEY}
    extraArgs:
      config.expand-env: "true"
    extraEnvFrom:
      - secretRef:
          name: lgtm-s3-creds
    extraEnv:
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca-certificates.crt
    extraVolumeMounts:
      - name: ca-certificates
        mountPath: /etc/ssl/certs
        readOnly: true
