tempo:
  extraVolumes:
    - name: ca-certificates
      configMap:
        name: trust-bundle
  replicas: 1
  persistence:
    enabled: true
    enableStatefulSetAutoDeletePVC: true
  serviceMonitor:
    enabled: true
  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-storage
          # The output values if minio was enabled are found here:
          # https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl#L213C2-L218C17
          # We cannot directly use them but it is a good reference.
          endpoint: https://minio.tales-tenant.svc
          # For unclear reasons the Kubernetes dollar-paren syntax is not
          # expanded but this is Loki's native expansion syntax with config.expand-env=true
          access_key: ${SECRET_ACCESS_KEY}
          secret_key: ${ACCESS_KEY_ID}
    extraArgs:
      config.expand-env: "true"
    extraEnvFrom:
      - secretRef:
          name: lgtm-s3-creds
    extraEnv:
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca-certificates.crt
    extraVolumeMounts:
      - name: ca-certificates
        mountPath: /etc/ssl/certs
        readOnly: true
