apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-mixin
  namespace: argocd
  labels:
    name: cilium-mixin
spec:
  project: default
  source:
    repoURL: https://github.com/symmatree/tales.git
    targetRevision: main
    path: cilium-mixin
    plugin:
      env:
        - name: TK_ENV
          value: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - ServerSideApply=true
